// ============================================================
// PHASE 0 — Mini Project 2: To-Do List CLI
// ============================================================
// Purpose: Practice OOP, List/Collections, and Control Flow through
//          a text-based To-Do List application (command line interface).
//          Concepts practiced:
//            - Class, constructor, instance method
//            - List (CRUD: add, remove, filter)
//            - DateTime for timestamps
//            - while loop + interactive menu
//            - Simple input validation
//            - toString() override for display
//
// How to run: dart run lib/phase0/mini_projects/todo/todo_app.dart
// ============================================================

import 'dart:io';

// ============================================================
// CLASS — TodoItem
// ============================================================

/// Represents a single to-do item in the application.
///
/// **Concepts demonstrated:**
/// - Class with multiple field types (int, String, bool, DateTime)
/// - `final` vs non-final fields
/// - Simple instance methods
/// - Override `toString()` for nice display
///
/// Each item has a unique ID, a title, a done/pending status, and
/// a creation timestamp. Status can be toggled (flipped) via `toggleDone()`.
class TodoItem {
  /// Unique ID for this item (auto-generated by [TodoManager]).
  final int id;

  /// Title or short description of the task.
  final String title;

  /// Whether this task has been completed.
  ///
  /// `false` = still pending/not done.
  /// `true`  = completed.
  bool isDone;

  /// Timestamp of when this item was created (auto-set on construction).
  final DateTime createdAt;

  // ── Constructor ─────────────────────────────────────────────
  // `id` and `title` are provided externally (by TodoManager).
  // `isDone` defaults to false — new tasks are always not done yet.
  // `createdAt` is auto-set to the current time.
  /// Creates a new to-do item.
  ///
  /// [id] must be unique (generated by [TodoManager]).
  /// [title] is the task title, must not be empty.
  /// [isDone] defaults to `false` — new tasks are always not done yet.
  TodoItem({required this.id, required this.title, this.isDone = false})
      : createdAt = DateTime.now();

  // ── Instance Method ─────────────────────────────────────────

  /// Flips the done/not-done status (toggle).
  ///
  /// If `isDone` was `false` → becomes `true`, and vice versa.
  /// Example:
  /// ```dart
  /// item.isDone; // false
  /// item.toggleDone();
  /// item.isDone; // true
  /// ```
  void toggleDone() {
    // `!` is the NOT operator — flips the bool value
    isDone = !isDone;
  }

  // ── Override toString() ─────────────────────────────────────

  /// Displays the to-do item in a human-readable format.
  ///
  /// Output format: `[✓] #1 Buy milk  (created: 14:30)`
  ///
  /// Overrides `Object.toString()` — automatically used when
  /// we `print(item)` or interpolate `'$item'`.
  @override
  String toString() {
    // Status icon: checkmark if done, empty box if not
    final statusIcon = isDone ? '✓' : ' ';

    // Format creation time — only show hour:minute for brevity
    final createdTime = _formatTime(createdAt);

    // Title with strikethrough effect (terminal doesn't support ~~,
    // so we use square brackets instead)
    final titleDisplay = isDone ? '[$title]' : title;

    return '[$statusIcon] #$id $titleDisplay  (created: $createdTime)';
  }

  // Format hour:minute:second from a DateTime
  // Private helper — only used inside this class
  String _formatTime(DateTime dt) {
    // padLeft(2, '0') → always ensure 2 digits, e.g. "9" → "09"
    final hour = dt.hour.toString().padLeft(2, '0');
    final minute = dt.minute.toString().padLeft(2, '0');
    final second = dt.second.toString().padLeft(2, '0');
    return '$hour:$minute:$second';
  }
}

// ============================================================
// CLASS — TodoManager
// ============================================================

/// Manages a collection of [TodoItem]s with full CRUD operations.
///
/// **Concepts demonstrated:**
/// - Encapsulation: `_todos` and `_nextId` are private (not directly accessible)
/// - List operations: add, remove (with `removeWhere`), filter (`where`)
/// - Auto-increment ID using `_nextId`
/// - Meaningful return values: `bool` to signal success/failure
///
/// Example usage:
/// ```dart
/// final manager = TodoManager();
/// manager.addTodo('Buy milk');
/// manager.toggleTodo(1);  // returns true if id found
/// manager.removeTodo(1);  // returns true if id found
/// ```
class TodoManager {
  // ── Private Fields ──────────────────────────────────────────
  // Prefixed with `_` so they cannot be accessed from outside the class.
  // This is the Encapsulation concept in OOP.

  /// List of all to-do items (private, managed internally).
  final List<TodoItem> _todos = [];

  /// Counter for the next ID — incremented each time an item is added.
  int _nextId = 1;

  // ── Methods ─────────────────────────────────────────────────

  /// Adds a new task to the list.
  ///
  /// [title] must not be empty (validated before calling this method).
  /// Returns the newly created [TodoItem] (useful for confirmation).
  ///
  /// ID is assigned automatically from [_nextId], then incremented.
  TodoItem addTodo(String title) {
    // Create a new item with the generated ID
    final item = TodoItem(id: _nextId, title: title);

    // Add it to the list
    _todos.add(item);

    // Increment the ID for the next item
    _nextId++;

    return item;
  }

  /// Removes an item by [id].
  ///
  /// Returns `true` if an item with the given [id] was found and
  /// successfully removed. Returns `false` if not found.
  ///
  /// Uses `removeWhere` — removes elements that satisfy the condition.
  bool removeTodo(int id) {
    // Check first whether an item with this id exists
    final previousLength = _todos.length;

    // removeWhere: remove all elements whose condition is true
    // Here: remove the item whose id matches the requested one
    _todos.removeWhere((item) => item.id == id);

    // If the list length changed, something was removed → return true
    return _todos.length < previousLength;
  }

  /// Flips the done/not-done status of the item with the given [id].
  ///
  /// Returns `true` if the item was found and toggled successfully.
  /// Returns `false` if no item with the given [id] exists.
  bool toggleTodo(int id) {
    // Find the item with the matching id
    // `where` + `firstOrNull` — safer than `firstWhere` which throws an error
    try {
      final item = _todos.firstWhere((item) => item.id == id);
      item.toggleDone();
      return true; // found & toggled successfully
    } catch (_) {
      return false; // not found
    }
  }

  /// Returns an unmodifiable copy of all items (pending + completed).
  ///
  /// Returns `List.unmodifiable` so it cannot be changed from outside.
  /// This protects the internal `_todos` from unexpected modifications.
  List<TodoItem> getAllTodos() {
    // `List.unmodifiable` → read-only, cannot add/remove from outside
    return List.unmodifiable(_todos);
  }

  /// Returns items that are NOT yet done (`isDone == false`).
  ///
  /// Uses `.where()` for filtering — this is a higher-order function
  /// that accepts a function (condition) as an argument.
  List<TodoItem> getPendingTodos() {
    // `.where()` → return an iterable that satisfies the condition
    // `.toList()` → convert the iterable to a List
    return _todos.where((item) => !item.isDone).toList();
  }

  /// Returns items that ARE completed (`isDone == true`).
  ///
  /// Same as [getPendingTodos] but with the opposite condition.
  List<TodoItem> getCompletedTodos() {
    return _todos.where((item) => item.isDone).toList();
  }
}

// ============================================================
// MAIN — Entry Point + Menu Loop
// ============================================================

/// Entry point of the To-Do List CLI application.
///
/// Displays an interactive menu and reads input from the user.
/// The loop keeps running until the user selects the "Exit" option.
///
/// **Concepts practiced in main():**
/// - while loop (menu loop)
/// - switch/case for menu routing
/// - stdin.readLineSync() for reading input
/// - Input validation (empty title, id must be a number)
void main() {
  // Opening banner
  _printBanner();

  // Create manager — this is one "session" of our to-do list
  final manager = TodoManager();

  // ── Menu Loop ───────────────────────────────────────────────
  // Keep looping while `isRunning` is still true.
  // User can exit by choosing option 7 (Exit).
  bool isRunning = true;

  while (isRunning) {
    _printMenu();

    // Read the user's choice from keyboard
    final input = stdin.readLineSync()?.trim() ?? '';

    // Route based on menu selection
    switch (input) {
      case '1':
        _handleAddTodo(manager);
      case '2':
        _handleViewAll(manager);
      case '3':
        _handleViewPending(manager);
      case '4':
        _handleViewCompleted(manager);
      case '5':
        _handleToggleTodo(manager);
      case '6':
        _handleDeleteTodo(manager);
      case '7':
        // Set flag to exit the while loop
        isRunning = false;
        print('\n👋 See you! Don\'t forget to get those tasks done!\n');
      default:
        // Invalid input — show error message
        print('\n⚠️  Choice "$input" is not valid. Enter a number 1-7.\n');
    }
  }
}

// ============================================================
// HELPER FUNCTIONS — Handler per Menu Item
// ============================================================

/// Adds a new to-do via user input.
///
/// Validates that the title is not empty before calling [TodoManager.addTodo].
void _handleAddTodo(TodoManager manager) {
  print('\n── Add New Task ──');
  stdout.write('Task title: ');
  final title = stdin.readLineSync()?.trim() ?? '';

  // Validation: title must not be empty
  if (title.isEmpty) {
    print('❌ Title cannot be empty. Task was not added.\n');
    return; // exit the function without adding
  }

  // Add to manager and capture the result
  final item = manager.addTodo(title);
  print('✅ Task added: $item\n');
}

/// Displays all to-dos (pending + completed).
void _handleViewAll(TodoManager manager) {
  print('\n── All Tasks ──');
  final todos = manager.getAllTodos();

  if (todos.isEmpty) {
    print('📋 No tasks yet. Add one with menu [1].\n');
    return;
  }

  // Show a stats summary first
  final completed = todos.where((t) => t.isDone).length;
  final pending = todos.length - completed;
  print('Total: ${todos.length} tasks  |  ✓ Completed: $completed  |  ○ Pending: $pending\n');

  // Display each item — toString() is already overridden in TodoItem
  for (final item in todos) {
    print('  $item');
  }
  print('');
}

/// Displays only pending (not-yet-done) to-dos.
void _handleViewPending(TodoManager manager) {
  print('\n── Pending Tasks (Not Done) ──');
  final pending = manager.getPendingTodos();

  if (pending.isEmpty) {
    print('🎉 No pending tasks. Everything is done!\n');
    return;
  }

  print('There are ${pending.length} unfinished tasks:\n');
  for (final item in pending) {
    print('  $item');
  }
  print('');
}

/// Displays only completed to-dos.
void _handleViewCompleted(TodoManager manager) {
  print('\n── Completed Tasks ──');
  final completed = manager.getCompletedTodos();

  if (completed.isEmpty) {
    print('📭 No completed tasks yet.\n');
    return;
  }

  print('${completed.length} tasks completed:\n');
  for (final item in completed) {
    print('  $item');
  }
  print('');
}

/// Asks the user for an ID and toggles the status of that task.
void _handleToggleTodo(TodoManager manager) {
  print('\n── Toggle Task Status ──');

  // Show all tasks first so the user knows their IDs
  final todos = manager.getAllTodos();
  if (todos.isEmpty) {
    print('📋 No tasks to toggle.\n');
    return;
  }

  // Show a brief list
  for (final item in todos) {
    print('  $item');
  }

  stdout.write('\nEnter the ID of the task to toggle: ');
  final inputId = stdin.readLineSync()?.trim() ?? '';

  // Validation: input must be a number
  final id = int.tryParse(inputId);
  if (id == null) {
    print('❌ "$inputId" is not a valid number.\n');
    return;
  }

  // Toggle and check the result
  final success = manager.toggleTodo(id);
  if (success) {
    // Find the newly toggled item to show its new status
    final item = manager.getAllTodos().firstWhere((t) => t.id == id);
    final newStatus = item.isDone ? 'DONE ✓' : 'PENDING ○';
    print('✅ Task #$id is now: $newStatus\n');
  } else {
    print('❌ No task found with ID #$id.\n');
  }
}

/// Asks the user for an ID and deletes that task.
void _handleDeleteTodo(TodoManager manager) {
  print('\n── Delete Task ──');

  final todos = manager.getAllTodos();
  if (todos.isEmpty) {
    print('📋 No tasks to delete.\n');
    return;
  }

  // Show the list so the user knows available IDs
  for (final item in todos) {
    print('  $item');
  }

  stdout.write('\nEnter the ID of the task to delete: ');
  final inputId = stdin.readLineSync()?.trim() ?? '';

  // Validation: must be a number
  final id = int.tryParse(inputId);
  if (id == null) {
    print('❌ "$inputId" is not a valid number.\n');
    return;
  }

  // Confirm before deleting
  stdout.write('Are you sure you want to delete task #$id? (y/n): ');
  final confirmation = stdin.readLineSync()?.trim().toLowerCase() ?? '';

  if (confirmation != 'y' && confirmation != 'yes') {
    print('🚫 Deletion cancelled.\n');
    return;
  }

  // Delete and check the result
  final success = manager.removeTodo(id);
  if (success) {
    print('🗑️  Task #$id successfully deleted.\n');
  } else {
    print('❌ No task found with ID #$id.\n');
  }
}

// ============================================================
// HELPER FUNCTIONS — Display
// ============================================================

/// Displays the welcome banner when the application first starts.
void _printBanner() {
  print('');
  print('╔══════════════════════════════════════════╗');
  print('║      📝  To-Do List CLI — Phase 0        ║');
  print('║   Dart CLI Mini Project #2               ║');
  print('╚══════════════════════════════════════════╝');
  print('');
}

/// Displays the menu options at each iteration of the loop.
void _printMenu() {
  print('┌──────────────────────────────────┐');
  print('│  MENU                            │');
  print('│  [1] Add New Task                │');
  print('│  [2] View All Tasks              │');
  print('│  [3] View Pending Tasks          │');
  print('│  [4] View Completed Tasks        │');
  print('│  [5] Toggle Done/Pending         │');
  print('│  [6] Delete Task                 │');
  print('│  [7] Exit                        │');
  print('└──────────────────────────────────┘');
  stdout.write('Choose menu: ');
}
