/// Phase 10.6 — Topic 02: gRPC (Google Remote Procedure Call)
///
/// gRPC uses Protocol Buffers (protobuf) for serialization and HTTP/2
/// for transport. It is faster and more efficient than REST+JSON for
/// high-throughput services.
///
/// When to use gRPC vs REST vs GraphQL:
/// - gRPC: service-to-service, streaming, mobile ↔ backend (same team)
/// - REST: public APIs, browser clients, third-party integrations
/// - GraphQL: flexible client queries, BFF (Backend For Frontend)
///
/// Key concepts covered:
/// 1. .proto file — service and message definitions
/// 2. protoc — generates Dart stubs from .proto
/// 3. Unary RPC — one request, one response
/// 4. Server streaming — one request, many responses over time
/// 5. Client streaming — many requests, one response
/// 6. Bidirectional streaming — many requests, many responses
/// 7. Metadata — authentication headers
/// 8. Interceptors — logging, auth, retry
import 'package:flutter/material.dart';

void main() => runApp(const _App());
class _App extends StatelessWidget {
  const _App();
  @override
  Widget build(BuildContext context) => MaterialApp(
    title: 'gRPC',
    debugShowCheckedModeBanner: false,
    theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.cyan), useMaterial3: true),
    home: const GrpcDemo(),
  );
}

class GrpcDemo extends StatelessWidget {
  const GrpcDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('02 — gRPC'), backgroundColor: Colors.cyan.shade700, foregroundColor: Colors.white),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          _card(color: Colors.cyan.shade50, child: const Text(
            'gRPC = RPC framework using protobuf + HTTP/2.\n\n'
            'Faster than REST/JSON: binary encoding + multiplexed streams.\n'
            'Type-safe: .proto defines the contract, protoc generates client/server code.',
            style: TextStyle(fontSize: 13),
          )),
          const SizedBox(height: 16),

          _h('1. Define the Proto File', Colors.cyan.shade700),
          _code(r'''
// protos/chat.proto
syntax = "proto3";

package chat;

option dart_out = "lib/src/generated";  // output directory

// Message types (like classes, serialized to binary)
message ChatMessage {
  string id = 1;           // field number — determines binary encoding
  string sender_id = 2;
  string content = 3;
  int64  timestamp = 4;    // Unix milliseconds
}

message SendMessageRequest {
  string chat_room_id = 1;
  string content = 2;
}

message SendMessageResponse {
  ChatMessage message = 1;
  bool success = 2;
}

message StreamMessagesRequest {
  string chat_room_id = 1;
  int64  since_timestamp = 2;
}

// Service definition — what the server exposes
service ChatService {
  // Unary: one request → one response (like HTTP GET/POST)
  rpc SendMessage(SendMessageRequest) returns (SendMessageResponse);

  // Server streaming: one request → many responses over time
  rpc StreamMessages(StreamMessagesRequest) returns (stream ChatMessage);

  // Bidirectional streaming: continuous message exchange
  rpc ChatStream(stream ChatMessage) returns (stream ChatMessage);
}

# Generate Dart code:
dart pub global activate protoc_plugin
protoc --dart_out=grpc:lib/src/generated --plugin=protoc-gen-dart protos/chat.proto'''),

          const SizedBox(height: 20),
          _h('2. Dart gRPC Client', Colors.blue),
          _code(r'''
# pubspec.yaml
dependencies:
  grpc: ^4.0.1
  protobuf: ^3.1.0

// lib/services/chat_grpc_client.dart
import 'package:grpc/grpc.dart';
import 'src/generated/chat.pbgrpc.dart';   // generated by protoc

class ChatGrpcClient {
  late final ClientChannel _channel;
  late final ChatServiceClient _stub;

  ChatGrpcClient.connect({required String host, required int port}) {
    _channel = ClientChannel(
      host,
      port: port,
      options: const ChannelOptions(
        // PRODUCTION: use TLS
        credentials: ChannelCredentials.secure(),
        // Development:
        // credentials: ChannelCredentials.insecure(),
      ),
    );

    _stub = ChatServiceClient(
      _channel,
      options: CallOptions(
        // Auth token as gRPC metadata header
        metadata: {'authorization': 'Bearer $token'},
        timeout: const Duration(seconds: 15),
      ),
    );
  }

  // ── Unary: send one message ─────────────────────────────────────
  Future<ChatMessage> sendMessage(String roomId, String content) async {
    final response = await _stub.sendMessage(SendMessageRequest(
      chatRoomId: roomId,
      content: content,
    ));
    return response.message;
  }

  // ── Server streaming: receive message stream ────────────────────
  Stream<ChatMessage> streamMessages(String roomId, {int sinceMs = 0}) {
    return _stub.streamMessages(StreamMessagesRequest(
      chatRoomId: roomId,
      sinceTimestamp: Int64(sinceMs),
    ));
  }

  // ── Bidirectional streaming: chat in real-time ──────────────────
  ResponseStream<ChatMessage> openChatStream() {
    // Returns a StreamController-like object
    return _stub.chatStream(
      // Input: a Stream of messages we send TO the server
      _outgoingMessages.stream,
    );
  }

  Future<void> close() => _channel.shutdown();
}

// Usage in Riverpod:
@riverpod
Stream<ChatMessage> chatMessages(ChatMessagesRef ref, String roomId) {
  final client = ref.watch(grpcClientProvider);
  return client.streamMessages(roomId);
  // Stream auto-cancels when provider is disposed
}'''),

          const SizedBox(height: 20),
          _h('3. Interceptors — Auth & Logging', Colors.orange),
          _code(r'''
// gRPC interceptors are like HTTP middleware — applied to every call

class AuthInterceptor implements ClientInterceptor {
  final TokenStorage _storage;
  const AuthInterceptor(this._storage);

  @override
  ResponseFuture<R> interceptUnary<Q, R>(
    ClientMethod<Q, R> method,
    Q request,
    CallOptions options,
    ClientUnaryInvoker<Q, R> invoker,
  ) {
    // Add auth token to every unary call
    final token = _storage.getAccessToken();
    final newOptions = options.mergedWith(CallOptions(
      metadata: {'authorization': 'Bearer $token'},
    ));
    return invoker(method, request, newOptions);
  }

  // Also intercept streaming calls...
}

// Register interceptor on the stub:
_stub = ChatServiceClient(
  _channel,
  interceptors: [AuthInterceptor(_storage), LoggingInterceptor()],
);'''),

          const SizedBox(height: 16),
          _card(color: Colors.cyan.shade50, child: const Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Key Takeaways', style: TextStyle(fontWeight: FontWeight.bold)),
              SizedBox(height: 8),
              Text('• .proto defines types and service — protoc generates Dart client'),
              Text('• 4 call types: unary, server stream, client stream, bidirectional'),
              Text('• Binary protobuf = ~5x smaller payload than JSON at same data'),
              Text('• Interceptors add auth/logging without touching business code'),
              Text('• Server streaming: ideal for real-time feeds, chat, dashboards'),
              Text('• gRPC requires HTTP/2 — works on Android/iOS, NOT in browsers (use gRPC-Web)'),
            ],
          )),
        ],
      ),
    );
  }
}

Widget _h(String t, Color c) => Padding(padding: const EdgeInsets.only(bottom: 6), child: Text(t, style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, color: c)));
Widget _code(String s) => Container(width: double.infinity, margin: const EdgeInsets.only(bottom: 4), padding: const EdgeInsets.all(12), decoration: BoxDecoration(color: const Color(0xFF1E1E2E), borderRadius: BorderRadius.circular(6)), child: SingleChildScrollView(scrollDirection: Axis.horizontal, child: Text(s, style: const TextStyle(fontFamily: 'monospace', fontSize: 11, color: Color(0xFFCDD6F4)))));
Widget _card({required Color color, required Widget child}) => Card(color: color, child: Padding(padding: const EdgeInsets.all(12), child: child));
