/// Phase 10.2 — Topic 01: Riverpod Generator
///
/// Riverpod Generator eliminates boilerplate by auto-generating provider
/// declarations from annotated functions and classes.
///
/// Without generator → you declare providers manually:
///   final counterProvider = StateNotifierProvider<CounterNotifier, int>(...)
///
/// With generator → you annotate and run build_runner:
///   @riverpod
///   class Counter extends _$Counter { ... }
///   // build_runner generates: counterProvider automatically
///
/// Key concepts covered:
/// 1. Setup: riverpod_annotation + riverpod_generator + build_runner
/// 2. @riverpod annotation for functions (simple providers)
/// 3. @Riverpod(keepAlive: true) — control auto-disposal
/// 4. Class-based notifiers: @riverpod class MyNotifier extends _$MyNotifier
/// 5. AsyncNotifierProvider — async data with loading/error/data states
/// 6. Family providers — parameterized providers via arguments
/// 7. Provider dependencies — ref.watch inside generated providers
/// 8. Testing generated providers — ProviderContainer overrides
///
/// How to regenerate after changing annotated code:
/// ```bash
/// dart run build_runner build --delete-conflicting-outputs
/// # or watch mode:
/// dart run build_runner watch --delete-conflicting-outputs
/// ```
import 'package:flutter/material.dart';

void main() => runApp(const _StandaloneApp());

class _StandaloneApp extends StatelessWidget {
  const _StandaloneApp();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Riverpod Generator',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const RiverpodGeneratorDemo(),
    );
  }
}

class RiverpodGeneratorDemo extends StatelessWidget {
  const RiverpodGeneratorDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('01 — Riverpod Generator'),
        backgroundColor: Colors.deepPurple,
        foregroundColor: Colors.white,
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          // ── Why use the generator? ──────────────────────────────────
          _card(
            color: Colors.deepPurple.shade50,
            child: const Text(
              'Riverpod Generator removes 80% of provider boilerplate.\n'
              'You write the logic; build_runner writes the provider wiring.\n\n'
              'Result: fewer typos, better type inference, consistent patterns.',
              style: TextStyle(fontSize: 13),
            ),
          ),
          const SizedBox(height: 16),

          // ── 1. Setup ────────────────────────────────────────────────
          _header('1. Setup', Colors.deepPurple),
          _code('''
# pubspec.yaml
dependencies:
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5   # annotations only (no code weight at runtime)

dev_dependencies:
  riverpod_generator: ^2.4.3    # generates .g.dart files
  build_runner: ^2.4.9
  custom_lint: ^0.7.0           # optional: Riverpod lint rules
  riverpod_lint: ^2.3.13        # optional: catches provider misuse

# Generate:
dart run build_runner build --delete-conflicting-outputs

# Watch (auto-regenerate on save):
dart run build_runner watch --delete-conflicting-outputs'''),

          const SizedBox(height: 20),

          // ── 2. Simple function provider ─────────────────────────────
          _header('2. Function Provider (@riverpod)', Colors.teal),
          _code(r'''
// lib/features/settings/providers/theme_provider.dart

import 'package:riverpod_annotation/riverpod_annotation.dart';
part 'theme_provider.g.dart';   // ← generated file

// @riverpod on a function = generates a Provider<T>
// The function body IS the provider's build logic
@riverpod
ThemeMode themeMode(ThemeModeRef ref) {
  // Read from SharedPreferences, Hive, etc.
  return ThemeMode.system;  // default
}

// @Riverpod(keepAlive: true) = provider is NEVER auto-disposed
// Use for global singletons (analytics, auth, etc.)
@Riverpod(keepAlive: true)
AppConfig appConfig(AppConfigRef ref) => AppConfig.fromEnv();

// Async function provider = generates FutureProvider<T>
@riverpod
Future<User> currentUser(CurrentUserRef ref) async {
  // ref is automatically typed as CurrentUserRef
  final auth = ref.watch(authServiceProvider);
  return auth.getCurrentUser();
}

// ── GENERATED by build_runner (theme_provider.g.dart): ──────────
// final themeModeProvider = Provider<ThemeMode>((ref) => themeMode(ref));
// final appConfigProvider = Provider<AppConfig>((ref) => appConfig(ref), ...keepAlive);
// final currentUserProvider = FutureProvider<User>((ref) => currentUser(ref));
//
// You NEVER write these manually again.'''),

          const SizedBox(height: 20),

          // ── 3. Class-based notifier ─────────────────────────────────
          _header('3. Class-Based Notifier', Colors.blue),
          _code(r'''
// lib/features/counter/providers/counter_provider.dart
import 'package:riverpod_annotation/riverpod_annotation.dart';
part 'counter_provider.g.dart';

// @riverpod on a class = generates a NotifierProvider<Counter, int>
// The class MUST extend _$ClassName (generated mixin with ref, state)
@riverpod
class Counter extends _$Counter {
  // build() = initial state (called once when first watched)
  @override
  int build() => 0;

  void increment() => state++;
  void decrement() => state = (state - 1).clamp(0, 999);
  void reset() => state = 0;
}

// Usage in widget (same as before — provider name is counterProvider):
// final count = ref.watch(counterProvider);
// ref.read(counterProvider.notifier).increment();

// ── GENERATED:
// final counterProvider = NotifierProvider<Counter, int>(Counter.new);'''),

          const SizedBox(height: 20),

          // ── 4. AsyncNotifier ────────────────────────────────────────
          _header('4. AsyncNotifier — Async State', Colors.orange),
          _code(r'''
// lib/features/transactions/providers/transaction_list_provider.dart
import 'package:riverpod_annotation/riverpod_annotation.dart';
part 'transaction_list_provider.g.dart';

@riverpod
class TransactionList extends _$TransactionList {
  // build() returns Future<T> → generates AsyncNotifierProvider
  // state is AsyncValue<List<Transaction>> automatically
  @override
  Future<List<Transaction>> build() async {
    // Automatically cancelled and rerun when dependencies change
    final repo = ref.watch(transactionRepoProvider);
    return repo.getAll();
  }

  // Optimistic add: update state immediately, then confirm
  Future<void> add(Transaction tx) async {
    // 1. Add to current list optimistically
    final current = state.requireValue;
    state = AsyncData([tx, ...current]);

    // 2. Persist to backend
    try {
      final saved = await ref.read(transactionRepoProvider).add(tx);
      // 3. Replace with server version (has ID)
      state = AsyncData([saved, ...current]);
    } catch (e, st) {
      // 4. Roll back on failure
      state = AsyncData(current);
      state = AsyncError(e, st);
    }
  }

  // Invalidate = dispose + re-run build() on next watch
  Future<void> refresh() => ref.refresh(transactionListProvider.future);
}

// Widget usage:
// final txs = ref.watch(transactionListProvider);
// txs.when(
//   loading: () => CircularProgressIndicator(),
//   error:   (e, _) => Text('Error: $e'),
//   data:    (list) => TransactionList(items: list),
// );'''),

          const SizedBox(height: 20),

          // ── 5. Family providers ─────────────────────────────────────
          _header('5. Family Providers (Parameterized)', Colors.green),
          _code(r'''
// Parameterized providers: one provider definition, many instances
// Each unique argument gets its own independent instance

@riverpod
Future<Transaction> transaction(TransactionRef ref, String id) async {
  // id is passed as a parameter — each id creates a separate provider
  return ref.watch(transactionRepoProvider).getById(id);
}

// Family notifier — stateful and parameterized
@riverpod
class TransactionDetail extends _$TransactionDetail {
  @override
  Future<Transaction> build(String id) async {
    return ref.watch(transactionRepoProvider).getById(id);
  }

  Future<void> delete() async {
    final id = arg; // 'arg' gives you the family parameter
    await ref.read(transactionRepoProvider).delete(id);
    ref.invalidateSelf(); // triggers rebuild/error state
  }
}

// Widget usage:
// final tx = ref.watch(transactionProvider('tx_123'));
// ref.read(transactionDetailProvider('tx_123').notifier).delete();

// IMPORTANT: Use @riverpod on families only when the parameter is:
// - A primitive (String, int, enum) — has consistent equality
// - An immutable value object with == overridden
// NEVER pass a mutable object (List, Map) as a family argument.'''),

          const SizedBox(height: 20),

          // ── 6. Provider dependencies ────────────────────────────────
          _header('6. Provider Dependencies', Colors.red),
          _code(r'''
// Providers can watch/read other providers — build_runner handles the wiring
@riverpod
class SearchResults extends _$SearchResults {
  @override
  Future<List<Transaction>> build(String query) async {
    // Debounce: wait 300ms before fetching (avoids too many requests)
    await Future.delayed(const Duration(milliseconds: 300));

    // Watch other providers — this provider re-runs when they change
    final repo  = ref.watch(transactionRepoProvider);
    final filter = ref.watch(activeFilterProvider);

    // Combine query + filter
    return repo.search(query: query, filter: filter);
  }
}

// ref.watch vs ref.read inside a provider:
// ref.watch(x) → rebuilds THIS provider when x changes
// ref.read(x)  → one-time read, no rebuild subscription
// ref.listen(x, (prev, next) => ...) → side effect on change (e.g. analytics)'''),

          const SizedBox(height: 16),
          _card(
            color: Colors.deepPurple.shade50,
            child: const Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Key Takeaways', style: TextStyle(fontWeight: FontWeight.bold)),
                SizedBox(height: 8),
                Text('• @riverpod on function → Provider<T> or FutureProvider<T>'),
                Text('• @riverpod on class → NotifierProvider or AsyncNotifierProvider'),
                Text('• build_runner generates the *Provider variable automatically'),
                Text('• Family: add a parameter to the function/build() for parameterized providers'),
                Text('• keepAlive: true prevents auto-disposal (use for global services)'),
                Text('• ref.watch inside build() creates reactive dependencies'),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

Widget _header(String t, Color c) => Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Text(t, style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, color: c)),
    );

Widget _code(String code) => Container(
      width: double.infinity,
      margin: const EdgeInsets.only(bottom: 4),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: const Color(0xFF1E1E2E), borderRadius: BorderRadius.circular(6)),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Text(code, style: const TextStyle(fontFamily: 'monospace', fontSize: 11, color: Color(0xFFCDD6F4))),
      ),
    );

Widget _card({required Color color, required Widget child}) =>
    Card(color: color, child: Padding(padding: const EdgeInsets.all(12), child: child));
