/// Domain repository interface: ITransactionRepository
///
/// Defines WHAT the domain layer needs from a transaction data source,
/// without specifying HOW the data is stored or fetched.
///
/// This is the Repository Pattern in action:
/// - The interface lives in the Domain layer (no external dependencies)
/// - The implementation lives in the Data layer (Hive, Firestore, etc.)
/// - The presentation layer calls the interface — it never knows about Hive
///
/// To swap from Hive to Firestore: create a new implementation class
/// and update the DI registration. Zero changes to domain or UI code.

import '../entities/transaction.dart';

/// Abstract interface for transaction persistence operations.
///
/// All methods return [List<Transaction>] or void — never raw data types
/// from the data layer (no Maps, no DTOs, no Hive objects).
abstract interface class ITransactionRepository {
  // ── Read ──────────────────────────────────────────────────────────────────

  /// Returns all transactions for [walletId], sorted by date descending.
  ///
  /// Returns an empty list if no transactions exist — never throws for
  /// an empty result.
  Future<List<Transaction>> getTransactions({required String walletId});

  /// Returns transactions filtered by [month] (year + month only).
  ///
  /// [month] — only the year and month fields are used; day/time is ignored.
  Future<List<Transaction>> getTransactionsByMonth({
    required String walletId,
    required DateTime month,
  });

  /// Returns transactions for a [category] within [month].
  ///
  /// Used by the budget tracking feature to compute spent vs limit.
  Future<List<Transaction>> getTransactionsByCategoryAndMonth({
    required TransactionCategory category,
    required DateTime month,
  });

  /// Computes the total balance for [walletId] by summing all transactions.
  ///
  /// income adds, expense subtracts, transfer has no net effect on the wallet
  /// unless a destination wallet is also tracked.
  Future<double> getBalance({required String walletId});

  // ── Write ─────────────────────────────────────────────────────────────────

  /// Persists a new transaction and returns the saved entity (with ID).
  ///
  /// The ID may be generated by the data layer (Hive auto-increment or UUID).
  Future<Transaction> addTransaction(Transaction transaction);

  /// Replaces an existing transaction identified by [transaction.id].
  ///
  /// Throws [ArgumentError] if no transaction with that ID exists.
  Future<Transaction> updateTransaction(Transaction transaction);

  /// Permanently removes the transaction with [id].
  ///
  /// Returns normally even if no transaction with that ID exists (idempotent).
  Future<void> deleteTransaction(String id);

  // ── Streaming (optional for real-time UI) ─────────────────────────────────

  /// Emits the latest transaction list for [walletId] whenever data changes.
  ///
  /// Useful with Riverpod StreamProvider for live-updating lists.
  /// With Hive: use Hive.box.watch(); with Firestore: use snapshots().
  Stream<List<Transaction>> watchTransactions({required String walletId});
}
